# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_param simulator.modelsimInstallPath D:/modelsim/win32pe
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/thb20/Desktop/Big_homework/touch_board/touch_board.cache/wt [current_project]
set_property parent.project_path C:/Users/thb20/Desktop/Big_homework/touch_board/touch_board.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
add_files -quiet C:/Users/thb20/Desktop/Big_homework/touch_board/touch_board.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.dcp
set_property used_in_implementation false [get_files C:/Users/thb20/Desktop/Big_homework/touch_board/touch_board.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.dcp]
add_files -quiet c:/Users/thb20/Desktop/Big_homework/touch_board/touch_board.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.dcp
set_property used_in_implementation false [get_files c:/Users/thb20/Desktop/Big_homework/touch_board/touch_board.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.dcp]
read_verilog -library xil_defaultlib {
  C:/Users/thb20/Desktop/Big_homework/touch_board/touch_board.srcs/sources_1/new/RegInit.v
  C:/Users/thb20/Desktop/Big_homework/touch_board/touch_board.srcs/sources_1/new/VGAPosControl.v
  C:/Users/thb20/Desktop/Big_homework/touch_board/touch_board.srcs/sources_1/new/Sccb.v
  C:/Users/thb20/Desktop/Big_homework/touch_board/touch_board.srcs/sources_1/new/Display7.v
  C:/Users/thb20/Desktop/Big_homework/touch_board/touch_board.srcs/sources_1/new/CameraAttrSet.v
  C:/Users/thb20/Desktop/Big_homework/touch_board/touch_board.srcs/sources_1/new/Binarization.v
  C:/Users/thb20/Desktop/Big_homework/touch_board/touch_board.srcs/sources_1/new/VGA.v
  C:/Users/thb20/Desktop/Big_homework/touch_board/touch_board.srcs/sources_1/imports/new/CameraGetData.v
  C:/Users/thb20/Desktop/Big_homework/touch_board/touch_board.srcs/sources_1/new/Bluetooth.v
  C:/Users/thb20/Desktop/Big_homework/touch_board/touch_board.srcs/sources_1/new/LinearFitting.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/thb20/Desktop/Big_homework/touch_board/touch_board.srcs/constrs_1/new/top.xdc
set_property used_in_implementation false [get_files C:/Users/thb20/Desktop/Big_homework/touch_board/touch_board.srcs/constrs_1/new/top.xdc]


synth_design -top LinearFitting -part xc7a100tcsg324-1


write_checkpoint -force -noxdef LinearFitting.dcp

catch { report_utilization -file LinearFitting_utilization_synth.rpt -pb LinearFitting_utilization_synth.pb }
